- .github/ISSUE_TEMPLATE/🐞-bug-template.md
- .github/ISSUE_TEMPLATE/💡-issue-template.md
- .github/pull_request_template.md
- .github/workflows/ios-pr-test.yml
- README.md
> Add: Github Actions CI 설정

- BE/layover/package-lock.json
- BE/layover/package.json
- BE/layover/src/app.module.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/utils/jwtUtils.ts
- apple oauth 기능 구현
- IPA 배포를 위한 정적 파일 배포 기능
- server-static 패키지 설치
- 로그인 api 응답 body 필드명 변경
- apple oauth 기능 구현
#22
> feat: Apple OAuth, IPA 배포 기능

- BE/layover/src/main.ts
- ssl 인증을 위한 포트 번호 변경
- ssl 인증을 위한 포트 번호 변경
- ssl 인증을 위한 포트 번호 변경
#30
> feat: 포트 번호 80으로 변경 (임시?)

- BE/layover/src/main.ts
- https 통신을 위한 코드 수정
- https 인증서 설치
#37
> feat: ssl/tls 인증서 설치 관련 코드 추가

- .gitignore
- BE/layover/src/custom-exception.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.service.ts
- apple oauth가 Post인데 Get이었음..
> fix: 오타 수정!!! (세글자)

- BE/layover/src/oauth/oauth.service.ts
> fix: api 간단 수정(멤버해시 응답하도록)

- BE/layover/src/app.module.ts
- BE/layover/src/custom-exception.ts
- BE/layover/src/database/database.module.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.module.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/pipes/jwt.validation.pipe.ts
- BE/layover/src/utils/jwtUtils.ts
- 환경 변수 설정 수정(각 모듈별로 import해야 환경변수가 잘 로드됨)
- jwt 관련 함수들은 jwtUtils.ts로 이동시킴
- 로그인 과정 예외처리 구현
- 명시할만한 변경사항은 X
#22
> feat: 로그인 예외처리

- BE/layover/src/member/member.service.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/pipes/custom-header.decorator.ts
- BE/layover/src/pipes/jwt.validation.pipe.ts
- 모든 api에서 토큰은 헤더로 받아오도록 변경됨. 따라서 jwt 유효성을 검증하던 파이프 구현을 변경함.
- 없음
close #77
> fix: JWT validation pipe 수정

- BE/layover/src/board/board.controller.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/pipes/jwt.validation.pipe.ts
- BE/layover/src/response/custom-response.ts
- BE/layover/src/response/ecustom-code.jenum.spec.ts
- BE/layover/src/response/ecustom-code.jenum.ts
- BE/layover/src/utils/jwtUtils.ts
- status code 올바르게 수정
close #94
> fix: status code 수정

- BE/layover/.eslintrc.js
- BE/layover/.prettierrc
- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.entity.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/board/dtos/encoding-callback.dto.ts
- BE/layover/src/board/dtos/upload-callback.dto.ts
- BE/layover/src/main.ts
- BE/layover/src/member/member.service.ts
- BE/layover/src/video/video.entity.ts
- BE/layover/src/video/video.service.ts
- board 및 video 관련 로직 작성
- eslint, 프리티어 수정 
eslint 프리티어 줄 바꿈 안되게 바꾸었습니당
close #66
> chore: 비디오 업로드 로직 개발 및 수정

- BE/layover/src/member/dtos/introduce-res.dto.ts
- BE/layover/src/member/member.service.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.service.ts
- 오타 수정
- DTO 활용
- find 대신 findOne 사용
close #78 #85
> fix: 리뷰 반영

- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.entity.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/video/video.service.ts
- callback 기본 형태 추가
- callback 테스트용 로거 찍기
- 컨트롤러에서 로거 사용
> feat: callback 추가 및 로거 테스트

- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/main.ts
- BE/layover/src/member/dtos/profile-presigned-url-res.dto.ts
- BE/layover/src/member/dtos/profile-presigned-url.dto.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/member/member.entity.ts
- BE/layover/src/member/member.service.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/utils/s3Utils.ts
- 프로필 이미지 presigned url 요청 api 구현
- 환경변수이름 수정
종인님이 작성해주신 코드 그대로 쓰니 잘 올라갔음..(감사합니다)
close #106
> feat: 프로필 이미지 presigned url 요청 api 구현

- BE/layover/src/main.ts
- BE/layover/src/member/dtos/member-infos-res.dto.ts
- BE/layover/src/member/dtos/profile-presigned-url-res.dto.ts
- BE/layover/src/member/dtos/profile-presigned-url.dto.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/member/member.service.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/pipes/jwt.validation.pipe.ts
- BE/layover/src/response/ecustom-code.jenum.ts
- BE/layover/src/utils/s3Utils.ts
- 회원 정보 get 요청 api 구현
- 회원 프로필 이미지 다운로드 presigned url 생성 함수 구현
close #131
> feat: 회원 정보 GET API

- BE/layover/src/member/dtos/member-infos-res.dto.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/response/ecustom-code.jenum.ts
- 다른 유저의 정보를 가져올 수 있는 api 구현 (/member/{id})
없습니당
close #139
> feat: 타인 정보 가져오는 api 구현

- BE/layover/src/app.module.ts
- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.module.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/board/dtos/board-res-dto.ts
- BE/layover/src/board/dtos/boards-res.dto.ts
- BE/layover/src/main.ts
- BE/layover/src/tag/tag.entity.ts
- BE/layover/src/tag/tag.module.ts
- BE/layover/src/tag/tag.provider.ts
- BE/layover/src/tag/tag.service.ts
- 홈 화면에서 보여줄 데이터 10개를 무작위로 가져온다.
- db의 데이터 총 수를 센다음 임의의 숫자를 정한다. 그리고 거기서부터 10개를 가져온다.
- 랜덤으로 데이터를 가져오는데 "페이징" 의 의미가 없다고 생각해서 그 부분은 제외
이건 일단 더미데이터를 내일 넣어보고 테스트하기로...
#107 
close #107
> feat: 홈 화면 게시물 조회

- BE/layover/src/app.module.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/main.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/member/member.service.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/pipes/jwt.validation.pipe.ts
- BE/layover/src/report/dtos/report-res.dto.ts
- BE/layover/src/report/dtos/report.dto.ts
- BE/layover/src/report/report.controller.ts
- BE/layover/src/report/report.entity.ts
- BE/layover/src/report/report.module.ts
- BE/layover/src/report/report.provider.ts
- BE/layover/src/report/report.service.ts
- BE/layover/src/utils/interfaces/token.payload.d.ts
- BE/layover/src/utils/jwtUtils.ts
- 신고 요청 API 구현
- board service에 함수 하나 추가했습니다.
없음.
(위에놈들은 board 테이블에 데이터 없을때 진행하니까 저렇게 board id가 NULL로 됐었음. 제일 아래처럼 board table에 데이터 넣고 테스트해보니 잘 됨)
close #150
> feat: 신고 API 구현

- iOS/Layover/Layover.xcodeproj/project.pbxproj
- iOS/Layover/Layover/AppDelegate.swift
- iOS/Layover/Layover/Services/System.swift
- iOS/Layover/Layover/Services/UserDefaults/UserDefaultStored.swift
- 앱 재설치 시 키체인 삭제 구현
- 전체 앱의 상태를 관리하는 System 객체를 구현했습니다.
- 해당 객체를 통해서, 사용자가 앱을 이전에 삭제했다가 새로 설치된 상태였으면, 기존에 남아있던 키체인을 삭제합니다.
close #157
> feat: 키체인 삭제 구현

- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.entity.ts
- BE/layover/src/board/board.service.ts
- tag를 기준으로 데이터를 가져옵니다.
close #109
> feat:  tag별 데이터 가져오기

- BE/layover/src/board/board.service.ts
- BE/layover/src/board/dtos/board-res-dto.ts
- BE/layover/src/board/dtos/create-board-res.dto.ts
- BE/layover/src/board/dtos/create-board.dto.ts
> :wrench: 위도 경도 수정

- iOS/Layover/Layover.xcodeproj/project.pbxproj
- iOS/Layover/Layover/Network/Provider/Provider.swift
- iOS/Layover/Layover/Scenes/Home/Cell/HomeCarouselCollectionViewCell.swift
- iOS/Layover/Layover/Scenes/Home/HomeConfigurator.swift
- iOS/Layover/Layover/Scenes/Home/HomeInteractor.swift
- iOS/Layover/Layover/Scenes/Home/HomeModels.swift
- iOS/Layover/Layover/Scenes/Home/HomePresenter.swift
- iOS/Layover/Layover/Scenes/Home/HomeRouter.swift
- iOS/Layover/Layover/Scenes/Home/HomeViewController.swift
- iOS/Layover/Layover/Scenes/Home/HomeWorker.swift
- iOS/Layover/Layover/Workers/Mocks/MockHomeWorker.swift
- iOS/Layover/Layover/Workers/Mocks/StubAuthManager.swift
- Home VIP 사이클 적용
- MockHomeWorker 적용
- Home 셀 썸네일 이미지 적용 
- Home 셀 선택 개선
> [!NOTE]
> MockWorker 구현 시 StubAuthManager 주입
- 리프레시 토큰 로직이 provider에 들어가 있어서, provider에 StubAuthManager를 넣지 않으면 액세스토큰이 없는 것으로 간주되어서 로그인 화면으로 갑니다.
- 앞으로 MockWorker 제작할 때 StubAuthManager를 Provider에 주입해서 구현해주세요
close #144
> feat: Home VIP 적용, MockHomeWorker 구현 및 설정

- iOS/Layover/Layover.xcodeproj/project.pbxproj
- iOS/Layover/Layover.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- 제거후
- 인텔맥 기준 빌드타임 508초 -> 41초
- 린트 플러그인 삭제
- run script 추가
작동, 구현화면
close #194
> chore: SwiftLint 플러그인 삭제, run script 추가

- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.service.ts
- 삭제 기능 추가
- 인코딩 완료된 애들만 가져오기
- 삭제시 status 변경
- 게시물 불러올때도 status 기반으로 가져옴
close #110
> feat: board 삭제 기능 및 필터링 추가

- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.service.ts
> feat: profile 게시글 조회 추가

- BE/layover/src/main.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/member/member.swagger.ts
- BE/layover/src/oauth/dtos/check-signup-res-dto.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.swagger.ts
- 회원가입 중복 여부를 확인하는 API를 구현
- 유저 정보를 가져오는 API를 하나로 통일
없습니다.
close #207
> feat: 회원가입 여부 확인 API 구현 및 프로필 GET 요청 하나로 통일

- BE/layover/package-lock.json
- BE/layover/package.json
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/pipes/jwt.validation.pipe.ts
- BE/layover/src/response/ecustom-code.jenum.ts
- BE/layover/src/utils/jwtUtils.ts
- apple id 검증 로직을 추가하였습니다.
- 스스로 힘으로 구현해보려고 하였으나... 공부하면 할수록 빙산의 일각이란 걸 알게 되었고...
- 아래와 같이 필요한 것들을 전부 검증해주는 착한 패키지가 있길래 가져와서 사용하기니 5분만에 해결.. 3시간동안 붙잡고 있던 놈을 놓아주기로 했습니다.
- verify-apple-id-token 패키지 설치
close #210
> Feat: apple id 토큰 검증 로직 추가

- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.service.ts
- 회원가입 여부 확인 필드명을 `isAlreadyExist`로 변경
- 오타 등등 수정
없습니다.
작동, 구현화면
close #220
> fix: 회원가입 여부 확인 필드명 변경 및 자잘한 수정

- BE/layover/src/board/board.service.ts
- BE/layover/src/tag/tag.module.ts
- BE/layover/src/tag/tag.repository.ts
- BE/layover/src/tag/tag.service.ts
> refactor: 태그 관련 리팩토링

- BE/layover/src/board/board.service.spec.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/member/member.module.ts
- BE/layover/src/member/member.repository.ts
- BE/layover/src/member/member.service.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/report/report.service.ts
- Member Service / Repository 분리
- 종인님이랑 합의한대로 함수 이름들 변경
없습니다.
close #245
> refactor: Member 리팩토링

- BE/layover/src/oauth/oauth.controller.spec.ts
- BE/layover/src/oauth/oauth.service.spec.ts
- oauth controller test code 작성
- oauth service test code 작성
- 없습니다.
close #249
> test: Oauth 모듈 테스트 코드

- BE/layover/src/member/member.controller.ts
- BE/layover/src/oauth/oauth.controller.spec.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.service.spec.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/pipes/jwt.validation.pipe.ts
- BE/layover/src/response/custom-response.ts
- BE/layover/src/response/ecustom-code.jenum.spec.ts
- BE/layover/src/response/ecustom-code.jenum.ts
- BE/layover/src/utils/jwtUtils.ts
- custom response 형태 수정
- 코드형태 말고, 의미로 바로 알 수 있도록 설정
- 사용되지 않는 customCode는 삭제
- 변경됨에 따라 수정되어야 할 부분 수정들...
- 이름 정하기 너무 어려움..
- exception하나로 퉁쳐서 좋긴한데 이 또한 쉽지 않다는걸 느낌 ㅠ,ㅠ
> refactor: custom response 리팩토링

- iOS/Layover/Layover.xcodeproj/xcshareddata/xcschemes/Layover.xcscheme
- iOS/Layover/Layover/Network/DTOs/Response.swift
- iOS/Layover/Layover/Network/Mock/MockData/CheckSignUp.json
- iOS/Layover/Layover/Network/Mock/MockData/CheckUserName.json
- iOS/Layover/Layover/Network/Mock/MockData/DeleteUser.json
- iOS/Layover/Layover/Network/Mock/MockData/GetMember.json
- iOS/Layover/Layover/Network/Mock/MockData/LoginData.json
- iOS/Layover/Layover/Network/Mock/MockData/PatchIntroduce.json
- iOS/Layover/Layover/Network/Mock/MockData/PatchProfileImage.json
- iOS/Layover/Layover/Network/Mock/MockData/PatchUserName.json
- iOS/Layover/Layover/Network/Mock/MockData/PostList.json
- iOS/Layover/Layover/Network/Mock/MockData/PostListEnd.json
- iOS/Layover/Layover/Network/Mock/MockData/PostListMore.json
- iOS/Layover/Layover/Network/Mock/MockData/ReportPlaybackVideo.json
- iOS/Layover/LayoverTests/Mocks/MockDatas/PostList.json
- 공통 Response DTO 필드 제거
- 클라가 따로 활용하지 않는 커스텀 코드 필드를 서버측에서 제거한다고 하여 저희도 목과 DTO에서  필드를 제거했습니다.
- 앞으로는 아래와 같은 형식으로 response가 온다고 합니다!
- 언제 누락됐는지 모르는... 스킴을 추가했습니다
close #253
> chore: 공통 Response DTO 필드 제거 + 스킴 추가

- BE/layover/src/utils/s3Utils.ts
> bug: mov 분기 처리

- BE/layover/src/board/board.repository.ts
- BE/layover/src/board/board.service.ts
- 유저 id기준으로 게시글 모두 삭제(상태 DELETED 로 업데이트)
> feat: id별로 게시글 삭제

- BE/layover/src/board/board.controller.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/utils/s3Utils.ts
-  content-type key value 추가 및 로직 수정.
> chore: content-type key value 추가 및 로직 수정

- iOS/Layover/Layover/DesignSystem/LODescriptionView.swift
- iOS/Layover/Layover/Scenes/Home/HomeRouter.swift
- iOS/Layover/Layover/Scenes/Map/MapRouter.swift
- iOS/Layover/Layover/Scenes/Playback/Cell/PlaybackCell.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackInteractor.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackModels.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackPresenter.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackView.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackViewController.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackWorker.swift
- iOS/Layover/Layover/Workers/Mocks/MockPlaybackWorker.swift
UI를 개선했습니다. UI도 여러부분 삐그덕 거리는 곳이 있어서 다 해결...?해주었습니다.
그라디언트 검은색 배경 너무 안 이뻐서 차라리 텍스트를 페이드 줄 수 있도록 했어요.
프로필 이미지 로드도 추가했습니다.
위치도 이제 위도, 경도에 맞게 시만 출력합니다.
https://github.com/boostcampwm2023/iOS09-Layover/assets/44396392/0ae206c9-1c0e-4c16-b00c-1b7bf9a53c1d
close #256
> feat: UI개선, 프로필 이미지 추가

- BE/layover/src/board/board.fixture.ts
- BE/layover/src/board/board.module.ts
- BE/layover/src/board/board.repository.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/member/member.entity.ts
- BE/layover/src/member/member.module.ts
- BE/layover/src/member/member.repository.ts
- BE/layover/src/member/member.service.ts
- BE/layover/src/oauth/oauth.controller.spec.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.module.ts
- BE/layover/src/oauth/oauth.service.spec.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/report/report.controller.ts
- BE/layover/src/report/report.module.ts
- BE/layover/src/report/report.service.ts
- 회원 탈퇴시 바로 삭제되는 게 아니라 일단 Status 필드만 수정되도록 변경
- 종인님이 만든 함수 그때 이거 만들면서 한번 테스트해달라고 하셨는데, 해보니 잘 됐습니다~
- 없습니다.
close #276
> fix: 멤버 삭제 로직 수정

- iOS/Layover/Layover/Scenes/Map/MapRouter.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackInteractor.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackModels.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackPresenter.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackViewController.swift
- iOS/Layover/Layover/Scenes/Playback/PlaybackWorker.swift
- iOS/Layover/Layover/Scenes/Profile/ProfileRouter.swift
- iOS/Layover/Layover/Scenes/TagPlayList/TagPlayListRouter.swift
- iOS/Layover/Layover/Workers/Mocks/MockPlaybackWorker.swift
재생화면 페이징을 구현했습니다.
이제 진짜 쇼츠나 틱톡마냥 볼 수 있습니다.
https://github.com/boostcampwm2023/iOS09-Layover/assets/44396392/e25583e5-54f4-41b3-9866-c7314ca54632
close #174
> feat: 재생화면 페이징 구현

- BE/layover/src/board/board.repository.ts
- BE/layover/src/board/board.service.ts
- 지도 및 프로필에서 게시글 요청시 인코딩 중인 상태의 게시글도 보내준다.
> chore: 업로드 중인 상태도 반환하도록 설정

- BE/layover/src/board/board.controller.spec.ts
- BE/layover/src/board/board.controller.ts
- BE/layover/src/member/member.controller.ts
- BE/layover/src/member/member.module.ts
- BE/layover/src/member/member.service.ts
- BE/layover/src/oauth/oauth.controller.spec.ts
- BE/layover/src/oauth/oauth.controller.ts
- BE/layover/src/oauth/oauth.service.spec.ts
- BE/layover/src/oauth/oauth.service.ts
- BE/layover/src/pipes/jwt.validation.pipe.ts
- BE/layover/src/redis/redis.module.ts
- BE/layover/src/redis/redis.provider.ts
- BE/layover/src/report/report.controller.ts
- BE/layover/src/response/ecustom-code.jenum.ts
- https://www.youtube.com/watch?v=RQv86D0M5YY&t=5106s
- 위 영상을 보고 JWT로 인증을 하면 서버 효율측면에선 나쁘지 않지만 보안 관점에선 별로 좋지 않다는 걸 알고, 어느 정도 서버에서 제어 가능 하도록 액세스 토큰 블랙리스트를 추가
- 그 외에도 토큰 검증 과정 등에서 미흡한 부분을 좀 더 보완
- 기존에는 그냥 토큰 자체를 Redis에 저장했는데, 크기가 커서 각 토큰의 고유값인 jti를 활용하도록 변경
- 없습니다.
외에도 여러 시나리오 postman으로 테스트 완료. e2e 해봐야지 이제...
close #309
> feat: JWT를 이용한 인증 보안 강화

- BE/layover/Dockerfile
- BE/layover/Jenkinsfile_CD
- BE/layover/package-lock.json
- BE/layover/package.json
- BE/layover/src/utils/logging-interceptor.ts
- BE/layover/src/utils/my-logger.ts
- 기존 logger에서 파일 저장을 위해 custom logger로 변경
> chore: custom logger 설정

- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/board/dtos/encoding-callback.dto.ts
> chore: dto 및 로직 수정

- BE/layover/Jenkinsfile_CI
jenkins file 수정 (script 구문 추가)
> fix: jenkins file 수정

- BE/layover/Jenkinsfile_CD
- BE/layover/Jenkinsfile_CI
- BE/layover/docker-compose.yml
- BE/layover/src/board/board.controller.ts
- BE/layover/src/board/board.service.ts
- BE/layover/src/board/dtos/encoding-callback.dto.ts
> feat: release PR

- iOS/Layover/Layover.xcodeproj/project.pbxproj
- iOS/Layover/LayoverTests/Mocks/Workers/MockPlaybackWorker.swift
- iOS/Layover/LayoverTests/Scenes/Playback/PlaybackInteractorTests.swift
- iOS/Layover/LayoverTests/Scenes/Playback/PlaybackPresenterTests.swift
> test: 테스트 복원했습니다.
