iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Scenes/UIComponents/PlayerView.swift
AVPlayerLayer 공식문서 예제 코드를 참고해서 공통으로 사용할 수 있는 PlayerView를 구현했습니다.
필요한 인터페이스 메서드가 있으면 추가해서 사용하면 될 것 같습니다.
우선은 재생, 일시정지, 영상 시점 변경, 영상 비율 조정 4가지 메서드 정도만 넣어 두었습니다.
무려 프리뷰를 통해서도 영상 시청이 가능해요!
```swift
#Preview {
let view = PlayerView()
view.player = AVPlayer(url: URL(string: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8")!)
view.player?.isMuted = true
view.play()
return view
}
```
close #33
=> feat: PlayerView 구현

BE/layover/src/custom-exception.ts, BE/layover/src/oauth/oauth.controller.ts, BE/layover/src/oauth/oauth.service.ts, BE/layover/src/utils/hashUtils.ts
- 토큰 생성 함수를 따로 분리
- jwt 검증 과정 커스텀
- 토큰 생성 함수를 별도로 만듦. generateAccessRefreshTokens()
- jwt 검증을 그냥 `verifyAsync()` 함수로 했었는데, 이를 별도로 구현하여 사용. jwt 관련 예외를 세분화 하기 위함.
#22
=> fix: jwt 검증 과정 커스텀

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Scenes/UIComponents/LoopingPlayerView.swift
반복 재생을 위한 LoopingPlayerView를 구현했습니다.
반복 재생은 따로 AVPlayerLooper로 감싸주어야 하더군요
사용 방법은 프리뷰 코드를 참고하시면 되겠습니다.
```swift
#Preview {
let view = LoopingPlayerView()
view.prepareVideo(with: URL(string: "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8")!, timeRange: .init(start: .zero, end: .init(seconds: 3.0, preferredTimescale: CMTimeScale(1.0))))
view.play()
view.player?.isMuted = true
return view
}
```
작동, 구현화면
close #36
=> feat: 반복 재생이 되는 LoopingPlayerView 구현

iOS/Layover/Layover/Extensions/UICollectionViewLayout+.swift, iOS/Layover/Layover/Scenes/Home/HomeViewController.swift, iOS/Layover/Layover/Scenes/MapScene/MapCarouselCollectionViewCell.swift, iOS/Layover/Layover/Scenes/MapScene/MapInteractor.swift, iOS/Layover/Layover/Scenes/MapScene/MapModels.swift, iOS/Layover/Layover/Scenes/MapScene/MapPresenter.swift, iOS/Layover/Layover/Scenes/MapScene/MapViewController.swift, iOS/Layover/Layover/Scenes/UIComponents/LoopingPlayerView.swift
- 지도 탭 캐러셀에 LoopingPlayerView를 연동하여 3초 반복재생을 구현했습니다.
지금은 맥시멈 크기의 90%가 되는 순간 셀을 재생하게 됩니다.
공통으로 사용하는 부분이라 미리 말씀드렸어야하는데... 시간이 너무 늦어 우선 추가해보았습니다..
불필요하다거나 더 좋은 방법이 있다 싶으시면 말씀해주세용
player의 timeControlStatus 여부로 판단하도록 했습니다.
그리고 isPlaying 여부를 판단해서 play, pause하도록 수정했습니다..
```swift
var isPlaying: Bool {
get { player?.timeControlStatus == .playing }
}
```
- compositionalLayout의 수평스크롤 사용시 scrollDelegate가 트리거되지 않는다는 사실을 알게되었습니다..
- scrollDelegate를 통해 센터에 위치한 셀의 영상을 재생해주려고 했는데, 이게 현재로서는 불가능해보여서
visibleItemsInvalidationHandler를 다시 사용해야했습니다.
- 원래 만들어둔 익스텐션에 이스케이핑 클로저를 전달하는 방식도 생각해보았으나, 그것보다 그냥 동일한 섹션을 만들어주고 visibleItemsInvalidationHandler는 뷰컨에서 처리하는게 낫지않나 싶었습니다..ㅠ
- 최적의 방법은 아닌 것 같은데, 너무 오래 고민하다보니 차라리 다른 피쳐를 진행 후 다시 생각해보는게 생산적일 것 같다고 생각했습니다..!! 방법은 계속 …
=> Feat: 지도 탭 캐러셀 반복재생 및 `LoopingPlayerView`, `createCarouselLayout` 변경 사항

iOS/Layover/Layover/Scenes/Home/Cell/HomeCarouselCollectionViewCell.swift, iOS/Layover/Layover/Scenes/Home/HomeConfigurator.swift, iOS/Layover/Layover/Scenes/Home/HomeInteractor.swift, iOS/Layover/Layover/Scenes/Home/HomeModels.swift, iOS/Layover/Layover/Scenes/Home/HomePresenter.swift, iOS/Layover/Layover/Scenes/Home/HomeViewController.swift, iOS/Layover/Layover/Scenes/Home/HomeWorker.swift, iOS/Layover/Layover/Scenes/UIComponents/LoopingPlayerView.swift
- 홈 뷰 캐러셀 뷰에 데모 영상 재생을 구현했습니다.
- 처음부터 3초까지 반복재생됩니다.
- compositional layout의 visibleItemsInvalidationHandler 에서 0.9 이상의 scale 크기가 되었을 때 재생, 그 이하는 일시정지 하도록 했습니다.
- 해당 부분은 유경님께서 구현하신 방법 살펴보고 추후 수정할게요
- 영상 URL 넣는 부분은 우선 VIP 사이클을 거쳐서 넣어주도록 했는데, 추후 API 나오면 DTO 맞게 수정해야겠습니다. Worker로도 네트워킹 처리하구요. 
close #44
=> feat: 홈 탭 캐러셀에 PlayerView 연동

BE/layover/src/board/board.controller.ts, BE/layover/src/board/dtos/create-board.dto.ts, BE/layover/src/board/dtos/presigned-url-res.dto.ts, BE/layover/src/board/dtos/presigned-url.dto.ts, BE/layover/src/main.ts, BE/layover/src/oauth/dtos/apple-login.dto.ts, BE/layover/src/oauth/dtos/apple-signup.dto.ts, BE/layover/src/oauth/dtos/kakao-login.dto.ts, BE/layover/src/oauth/dtos/kakao-signup.dto.ts, BE/layover/src/oauth/dtos/token-res.dto.ts, BE/layover/src/oauth/oauth.controller.ts, BE/layover/src/response/custom-response.ts
- controller 스웨거 작성
- 기존 방식에서 dto 방식 변경
- controller 의 메소드마다 swagger 정보 작성
- req body, 성공, 응답 등 명시
- 기존의 Body() 와 변수를 사용한 방식에서 dto 방식으로 변경. 
- @ApiProperty 나 @ApiResponse 등의 데코레이터를 사용할려면 dto를 사용하는게 훨씬 깔끔해서 변경함
- 공통되는 에러 응답을 api마다 설정해두면 불편해서 어떻게 하면 좋을지 고민중
=> chore: 컨트롤러 스웨거 설정

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Network/AuthManager.swift, iOS/Layover/Layover/Network/EndPoint/EndPoint.swift, iOS/Layover/Layover/Network/EndPoint/Factories/LoginEndPointsFactory.swift, iOS/Layover/Layover/Resources/Assets.xcassets/appleLogo.imageset/Contents.json, iOS/Layover/Layover/Resources/Assets.xcassets/kakaoLogo.imageset/Contents.json, iOS/Layover/Layover/SceneDelegate.swift, iOS/Layover/Layover/Scenes/Home/HomeRouter.swift, iOS/Layover/Layover/Scenes/Login/LoginConfigurator.swift, iOS/Layover/Layover/Scenes/Login/LoginInteractor.swift, iOS/Layover/Layover/Scenes/Login/LoginModels.swift, iOS/Layover/Layover/Scenes/Login/LoginPresenter.swift, iOS/Layover/Layover/Scenes/Login/LoginRouter.swift, iOS/Layover/Layover/Scenes/Login/LoginViewController.swift, iOS/Layover/Layover/Scenes/Login/LoginWorker.swift, iOS/Layover/Layover/Services/UserDefaults/UserDefaultStored.swift
- 로그인 화면 UI 수정
- 카카오 로그인 로직 구현
- EndPoint 팩토리 구현
- UserDefault 래퍼 구현 및 AuthManager에 로그인 여부 프로퍼티 설정
> [!NOTE]
> 로그인 화면 UI를 변경했습니다.
- 버튼위에 라벨과 이미지가 올려져 있어서, 터치가 안되는 버그가 있었습니다. 
- iOS 15.0부터 사용가능한 UIButton.Configuration을 사용해 버튼을 구현하여 해결했습니다.
> [!NOTE]
> LoginEndPointFactory 를 선언했습니다.
- 팩토리 메서드로 EndPoint를 찍어낼 수 있도록 했습니다.
- 필요한 EndPoint들을 미리 설정해두고, Worker에서 사용하시면 될 것 같습니다.
- 다만, Factory 객체 프로퍼티에 대해서는 프로토콜로 추상화해서 의존성 역전 법칙을 지키도록 해주세요.
> [!NOTE]
> 카카오 로그인 로직을 구현했습니다.
- LoginInteractor에서는 큰 트랜잭션 로직을 수행하고, LoginWorker에게 세부적인 로직을 수행하게 하는 흐름입니다.
- 회원가입 여부 판단 API를 제외하고 나머지 부분만 우선 구현했습니다.
- 회원가입 여부에 따라 닉네임 수정 뷰, 로그인 수행 후 홈 뷰 routing으로 분기처리 메서드를 타도록 했습니다.
- 회원가입 완료 까지 처리하려면 SignUpScene의 코드도 수정해야 하기에, 이후 부분은 이슈를 파서 처리하겠습니다.
- 전에 CleanSwift 아키텍처에 대해 공부 할 때, 스레드 관리를 잘 해주어야 한다는 부분이 생각났습니다. 
- presenter …
=> feat: 카카오 로그인 로직 구현

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Layover.entitlements, iOS/Layover/Layover/Network/EndPoint/Factories/LoginEndPointFactory.swift, iOS/Layover/Layover/Network/Mock/MockData/LoginData.json, iOS/Layover/Layover/Scenes/Login/LoginConfigurator.swift, iOS/Layover/Layover/Scenes/Login/LoginInteractor.swift, iOS/Layover/Layover/Scenes/Login/LoginModels.swift, iOS/Layover/Layover/Scenes/Login/LoginViewController.swift, iOS/Layover/Layover/Scenes/Login/LoginWorker.swift, iOS/Layover/Layover/Workers/MockLoginWorker.swift
애플 소셜 로그인을 할 수 있습니다. 회원가입은 아직 미구현 상태이며 로그인을 성공했다고 가정합니다.
LoginViewController의 Worker를 MockLoginWorker로 변경해놓았습니다. 확인 바랍니다.
https://github.com/boostcampwm2023/iOS09-Layover/assets/44396392/08e8a596-4815-4aea-a771-61d9104df7ef
close #56
=> feat: 애플 로그인 API 요청 구현

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Network/EndPoint/Factories/SignUpEndPointFactory.swift, iOS/Layover/Layover/Scenes/Login/LoginInteractor.swift, iOS/Layover/Layover/Scenes/Login/LoginRouter.swift, iOS/Layover/Layover/Scenes/SignUpScene/SignUpConfigurator.swift, iOS/Layover/Layover/Scenes/SignUpScene/SignUpInteractor.swift, iOS/Layover/Layover/Scenes/SignUpScene/SignUpWorker.swift, iOS/Layover/Layover/Workers/MockLoginWorker.swift, iOS/Layover/Layover/Workers/MockSignUpWorker.swift
SignUp Worker가 Mock으로 들어가있습니다. 이 부분 확인하시고 작업하시길 바랍니다.
SignUpViewController에 token을 전달하는 과정에서
```swift
guard let source = dataStore,
var destination = signUpViewController.router?.dataStore
else { return }
destination.signUpType = .apple
destination.identityToken = source.appleLoginToken
``` 
이러한 방식을 써봤는데 어떠신지요. 의견을 들려주세요. inout쓰는 것 보단 이렇게 넘겨 주는게 괜찮은 방식이라고 생각해서요.
제가 call by reference 껌벅 죽는 편인데 Swift는 inout을 좀 피하는 분위기인 것 같더군요?
https://github.com/boostcampwm2023/iOS09-Layover/assets/44396392/ec89de7a-6c76-41cb-a41d-385c90522fff
close #121
=> feat: 애플 로그인 회원가입 로직 구현

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Scenes/Home/Cell/HomeCarouselCollectionViewCell.swift, iOS/Layover/Layover/Scenes/Home/HomeInteractor.swift, iOS/Layover/Layover/Scenes/Home/HomeViewController.swift
> [!NOTE] 
> 홈 뷰 캐러셀의 제목 라벨, 태그뷰를 구현했습니다.
- 태그 뷰는 UIButton과 UIStackView로 구현했고, 마지막에 Spacer 역할을 하는 빈 UIView()를 넣는 방식으로 설정했습니다.
close #125
=> feat: 홈 뷰 캐러셀 나머지 UI 구현

BE/layover/src/member/dtos/member-infos-res.dto.ts, BE/layover/src/member/member.controller.ts, BE/layover/src/member/member.service.ts, BE/layover/src/oauth/oauth.controller.ts, BE/layover/src/oauth/oauth.service.ts, BE/layover/src/utils/jwtUtils.ts, BE/layover/src/utils/swaggerUtils.ts
- swagger 코드를 간단하게 만들기 위해 상수화
- 회원가입 요청 때 이미 회원가입 된 유저라면 바로 로그인 되도록 처리함.
- jwt 토큰 각 필드에 공식문서에 작성된 의미에 맞는 값이 들어가도록 함
없습니다.
close #137
=> chore: swagger 정리, 회원가입 세부 로직 추가

iOS/Layover/Layover/SceneDelegate.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileViewController.swift, iOS/Layover/Layover/Scenes/Profile/ProfileRouter.swift, iOS/Layover/Layover/Scenes/SignUpScene/SignUpRouter.swift, iOS/Layover/Layover/Scenes/Tabbar/MainTabBarConfigurator.swift
- 뷰컨트롤러 푸시 할 경우, navigationBar 중첩되던 버그 수정
- 프로필 수정 뷰 진입 시 backgroundColor 투명으로 보이던 버그 수정
> [!WARNING]
> BaseViewController setUI() 메서드 오버라이드 시, 부모 메서드 호출
- 베이스 뷰컨의 setUI 메서드 오버라이드 해서 사용할 경우, 부모 메서드를 반드시 호출해 주어야 backgroundColor 설정이 적용됩니다.
> [!WARNING]
> navigationController navigationBar 중첩
- 중첩된 원인은 현재 라우팅 시나리오가 루트 뷰컨(네비게이션 컨트롤러) -> 메인 탭바 -> 각 탭별 네비게이션 컨트롤러
로 되어있기 때문에 메인 탭바로 진입 시에는 루트 네비게이션 컨트롤러의 네비바를 hide 설정해야합니다.
- 대신 로그인 뷰로 갈 경우는 다시 보이도록!
- 우리 앱은 Code Base UI 이기 떄문에, 나중에 스플래시 구현할 때도 주의해서 작업 해야겠네요.
close #142
=> bug: navigationBar 중첩 버그 수정

iOS/Layover/Layover/Scenes/Tabbar/MainTabBarConfigurator.swift
네비게이션 바 back button 이미지를 설정했습니다.
MainTabBarConfiguration에서 각 탭의 navigationController에 설정해 두었기 때문에 
푸시된 viewController의 backButton에 대해 신경쓰지 않으셔도 됩니다:)
close #155
=> feat: 네비게이션 바 back button 이미지 설정

iOS/Layover/Layover/AppDelegate.swift, iOS/Layover/Layover/Scenes/BaseViewController.swift, iOS/Layover/Layover/Scenes/SettingScene/SettingSceneViewController.swift, iOS/Layover/Layover/Scenes/Tabbar/MainTabBarConfigurator.swift
- navigationBar appearance 설정 수정
- tabBar appearance 설정 수정
- AppDelegate와 BaseViewController의 조합으로 appearance를 수정했습니다.
- Global appearance 설정은 AppDelegate에서 하고, 각 화면 별 backButton title은 각 화면에서 설정해야 한다고 하는군요.
- 다행히 우리는 BaseViewController를 통해서 해결할 수 있었네요. BaseViewController 로 빼길 잘한 것 같습니다.
- 이것도 setUI 메서드를 오버라이드 할 경우에, 부모메서드를 꼭 호출해야 합니다.
close #182
=> chore: navigationBar, tabBar appearance 관련 설정 수정

iOS/Layover/Layover/DesignSystem/LOTagStackView.swift, iOS/Layover/Layover/Scenes/Playback/Cell/PlaybackCell.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackViewController.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackWorker.swift
재생화면에서의 스택뷰 재사용 이슈가 있어 태그 스택뷰를 처리해 주는 작업을 했습니다.
UI에 관련된 내용이므로 prepareforreuse가 아닌 cell configure하는 부분에서 처리했습니다.
짜잘한 리팩토링(줄바꿈, 오타)수정이 있습니다.
없슴다.
https://github.com/boostcampwm2023/iOS09-Layover/assets/44396392/89f5d472-cf13-4112-999a-14bf36996b27
close #199
=> bug: 재생화면 스택 뷰 재사용 이슈

iOS/Layover/Layover/Network/Provider/Provider.swift
- 이미지 업로드용 업로드 메서드 구현
- 동영상 업로드용 백그라운드 업로드 메서드 구현
> [!NOTE] 
> 백그라운드 업로드 메서드 사용법
- 앱에서 progressBar를 표현하려면 업로드가 얼마나 진행되었는지 observing해야 하고, 
이는 URLSessionTaskDelegate의 didSendBodyData 인자가 있는 메서드를 통해 구현할 수 있습니다.
- 그래서 provider에서 해당 백그라운드 업로드 메서드를 호출하는 곳을 delegate로 주입할 수 있도록 인자를 열어두었습니다.
- 또한 해당 이벤트를 어떤 OperationQueue에서 받을 건지 지정해주어야 하는데, 우리는 보통 UI에 표기하기 위해 main에서 받을 테니까
OperationQueue.main을 넘기면 될 것 같네요
```swift
func backgroundUpload(fromFile: URL,
to url: String,
method: HTTPMethod = .PUT,
sessionTaskDelegate: URLSessionTaskDelegate? = nil,
delegateQueue: OperationQueue? = nil) async throws -> Data {
guard let url = URL(string: url) else { throw NetworkError.components }
var request = URLRequest(url: url)
request.httpMethod = method.rawValue
let backgroundSession = URLSession(configuration: …
```
=> feat: 업로드용 메서드 구현

BE/layover/src/board/board.controller.ts, BE/layover/src/board/board.service.ts, BE/layover/src/board/dtos/create-board.dto.ts, BE/layover/src/utils/swaggerUtils.ts
- tag 게시글 조회 및 프로필 게시글 조회시 페이지네이션 적용 (15개)
-> 3개의 그리드로 구성되어있기에 3의배수로 처리
-> 한 화면에 9개 정도 보이나 바로 콜 하는걸 방지하여 15개정도로 설정
- content와 tag를 optional로 처리
-> content와 tag없이도 게시물 생성 가능
close #203
=> feat: pagination 추가 및 버그 수정

BE/layover/src/board/board.controller.ts, BE/layover/src/main.ts, BE/layover/src/member/member.controller.ts, BE/layover/src/oauth/oauth.controller.ts, BE/layover/src/report/report.controller.ts
- 스웨거에서 jwt를 보내기 위하여 보안헤더 처리
- @ApiHeader 에서 @ApiBearerAuth로 처리 
api옆에 자물쇠가 생겼으며 클릭하여 값을 넣어줄 수 있음.
=> bug: jwt bearer 헤더 처리

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Network/DTOs/CheckSignUpDTO.swift, iOS/Layover/Layover/Network/EndPoint/Factories/LoginEndPointFactory.swift, iOS/Layover/Layover/Network/Mock/MockData/CheckSignUp.json, iOS/Layover/Layover/Scenes/Login/LoginInteractor.swift, iOS/Layover/Layover/Scenes/Login/LoginWorker.swift, iOS/Layover/Layover/Workers/Mocks/MockLoginWorker.swift
회원 가입 시 기존 가입 여부를 확인하는 API 엔드포인트를 연결했습니다.
지금은 True를 MockData로 놓아서 기존 회원가입 화면을 스킵하고 지나갑니다!
close #217
=> feat: 회원가입 시 기존 회원가입 여부 확인 네트워크 연결

iOS/Layover/Layover/Network/DTOs/CheckSignUpDTO.swift, iOS/Layover/Layover/Network/Mock/MockData/CheckSignUp.json, iOS/Layover/Layover/Network/Mock/MockData/LoginData.json, iOS/Layover/Layover/Scenes/Login/LoginInteractor.swift, iOS/Layover/Layover/Scenes/Login/LoginWorker.swift, iOS/Layover/Layover/Workers/Mocks/MockLoginWorker.swift
- 변경된 서버 API 필드명 `isAlreadyExist`로 회원가입 여부 DTO 필드명을 변경했습니다.
- MockURLProtocol.requestHandler data race 문제
- async let을 이용한 병렬 실행으로 카카오 로그인 로직을 애플과 동시에 맞춰주려고 했는데, Mock 메서드 내에서 실행되는 MockURLProtocol.requestHandler 설정부분에서 data race되어 decoding error가 발생하는 이슈가 있었습니다.
- 당장은 고치려면 Mock쪽을 건드려야 하게 되어서 우선은 각각을 await하는 것으로 변경했습니다.
close #222
=> chore: 변경된 서버 API 필드명으로 회원가입 여부 DTO 변경, 코드 리뷰 반영

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Network/EndPoint/Factories/DefaultPostManagerEndPointFactory.swift, iOS/Layover/Layover/Network/EndPoint/Factories/DeleteReportEndFactory.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackConfigurator.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackInteractor.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackModels.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackPresenter.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackViewController.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackWorker.swift, iOS/Layover/Layover/Scenes/Profile/ProfileRouter.swift, iOS/Layover/Layover/Scenes/Report/ReportInteractor.swift, iOS/Layover/Layover/Scenes/Report/ReportWorker.swift, iOS/Layover/Layover/Workers/Mocks/MockPlaybackWorker.swift, iOS/Layover/Layover/Workers/Mocks/MockReportWorker.swift
기존 pr 머지할 때 신고 버튼 넣었던 부분이 지워져서 다시 추가했습니다.
이번 pr도 이전 pr머지 받고 작업하려 했는데 너무 늦어질거 같아서. 이전 pr 머지 받고 충돌 없는지, 누락 된 부분 없는지 체크후 머지하겠습니다.
프로필 뷰도 원래 프로필의 전체 영상을 순회 하려고 했는데, 페이지네이션으로 구현된거 확인 후 무한스크롤 부분 떼주었습니다.
https://github.com/boostcampwm2023/iOS09-Layover/assets/44396392/103b891a-f19f-4e5a-b5da-ea61d3e64dc4
close #237
=> feat: 삭제 기능 추가

iOS/Layover/Layover/Network/DTOs/BoardDTO.swift, iOS/Layover/Layover/Network/Mock/MockData/PostList.json, iOS/Layover/Layover/Network/Mock/MockData/PostListMore.json, iOS/Layover/Layover/Scenes/Home/HomeConfigurator.swift, iOS/Layover/Layover/Scenes/Playback/Cell/PlaybackCell.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackInteractor.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackModels.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackPresenter.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackRouter.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackView.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackViewController.swift, iOS/Layover/Layover/Scenes/Profile/ProfileConfigurator.swift
재생화면 재사용이 잘못되어 재생화면이 중첩되어 들어가던 문제를 수정했습니다.
홈 워커도 목 떼고 실제 영상을 볼 수 있도록 했습니다.
그리고 서버에서 경도 위도 double로 내려줘서 그거에 맞게 목데이터랑 DTO수정했어요
close #243
=> bug: 재생화면 재사용 버그 수정

BE/layover/src/member/dtos/member-infos-res.dto.ts, BE/layover/src/member/member.controller.ts, BE/layover/src/member/member.swagger.ts, BE/layover/src/oauth/oauth.swagger.ts, BE/layover/src/report/report.swagger.ts, BE/layover/src/utils/swaggerUtils.ts
- 프로필 이미지 기본 이미지로 설정하는 api 새로 구현
- 이제 응답에 customCode가 사라져서 Member/Oauth/report 쪽 스웨거에 해당 사항 반영
- 없습니다.
close #263
=> feat: 기본 이미지 설정 api 구현 + 응답 형식 변경에 따른 스웨거 변경

iOS/Layover/Layover/SceneDelegate.swift, iOS/Layover/Layover/Scenes/Login/LoginRouter.swift, iOS/Layover/Layover/Scenes/Setting/SettingRouter.swift
네비게이션 바 중첩 버그를 수정했습니다.
- 해당 버그를 픽스하면서 안 사실인데, 원래는 tabBarController 자체가 navigationController에 embedded 되는 것 자체가 어색한 일이라고 합니다.
- 그래서 애플에서도 UITabbarController의 navigationController 프로퍼티는 항상 nil을 반환시키도록 했다고 합니다.
- 제가 UINavigationController 안에 UITabbarController를 포함시키게 된 건, 로그인 화면과 회원가입이 끝나면 메인 탭바를 오른쪽에서 푸시시키는 애니메이션을 주고자 했는데, 다른 방법을 고려하던가 하는게 좋을 것 같습니다.
- 물론 그래서 window의 rootViewController를 런타임에 할당으로 바꾸게 되면, 깜빡거리면서 UI적으로 어색한 형태가 나옵니다...
- 애니메이션을 주는 방법도 있는데 이 방법을 고려하던, 다른 방법을 고려하던 장기적으로는 대체할 방법을 찾아야 할 것 같습니다.
- 애니메이션은 적용하는게 좀 복잡해 보였어요
- 지금 고친 방법은 우선 메인에 진입 할때는 탭바 숨김을, 로그인으로 진입할때는 탭바를 보이도록 고친 것입니다.
close #260
=> bug: 실행 시 네비게이션 바 중첩 버그 수정

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover.xcodeproj/xcshareddata/xcschemes/Layover.xcscheme, iOS/Layover/Layover/Network/DTOs/MemberDTO.swift, iOS/Layover/Layover/Network/DTOs/PresignedURLDTO.swift, iOS/Layover/Layover/Network/DTOs/UploadVideoDTO.swift, iOS/Layover/Layover/Network/EndPoint/Factories/UploadPostEndPointFactory.swift, iOS/Layover/Layover/Network/EndPoint/Factories/UserEndPointFactory.swift, iOS/Layover/Layover/Network/Provider/Provider.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileConfigurator.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileInteractor.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileModels.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfilePresenter.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileRouter.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileViewController.swift, iOS/Layover/Layover/Scenes/Profile/ProfileInteractor.swift, iOS/Layover/Layover/Scenes/Profile/ProfileRouter.swift, iOS/Layover/Layover/Scenes/Profile/ProfileViewController.swift, iOS/Layover/Layover/Scenes/SignUpScene/SignUpPresenter.swift, iOS/Layover/Layover/Workers/Mocks/MockUserWorker.swift, iOS/Layover/Layover/Workers/UserWorker.swift
- 프로필 변경 화면 VIP 구현
- 프로필 화면 갱신 viewWIllAppear에서 하도록 변경
> [!NOTE] 
> PHPickerController로 프로필 이미지 데이터 접근 처리
- PHPickerResult의 itemProvider로 파일의 url에 접근할 수 있는 `loadFileRepresentation` 메서드는 인자로 넘겨주는 url이 해당 클로저 내에서만 유효한 임시적인 파일 url입니다.
- 하지만 해당 파일 데이터를 서버에 넘겨주고 처리해야 하는 메서드는 비동기 메서드 이기 때문에 해당 클로저가 종료될 시점내에 실행이 완료된다는 보장이 없습니다.
- 따라서 tmp 디렉토리 내에서 임시 url의 copyItem을 수행해서 파일을 복사하여, 실제 파일 데이터가 비동기 메서드 실행 시점에서도 유효하도록 하여 처리할 수 있었습니다.
- tmp 디렉토리는 지난번에 알려주신 대로 앱 종료시 디렉토리가 비워지지만, 데이터가 쌓일 것을 대비해 처리가 끝나면 명시적으로 지워지도록 처리했습니다.
그 외, 프로필 변경 이후 프로필 화면으로 다시 복귀할 때 변경한 데이터로 적용시켜주기 위해, 
viewWillAppear로 프로필 데이터를 가져오는 시점을 변경했습니다.
close #236
=> feat: 프로필 변경 화면 VIP 구현

iOS/Layover/Layover/DesignSystem/LOImageLabel.swift, iOS/Layover/Layover/Extensions/Notification.Name+.swift, iOS/Layover/Layover/Network/Provider/Provider.swift, iOS/Layover/Layover/SceneDelegate.swift, iOS/Layover/Layover/Scenes/EditVideo/EditVideoInteractor.swift, iOS/Layover/Layover/Scenes/EditVideo/EditVideoViewController.swift, iOS/Layover/Layover/Scenes/UIComponents/Toast.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostViewController.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostWorker.swift
- videoEdit 뷰에서 실제 Editor로 진입시 영상 멈추기, 다시 videoEdit으로 돌아갈 경우 play
- videoEditor로 영상 편집 후 해당 영상에 기존 mute 여부 반영하기
- 앗차차, 그리고 편집한 영상 url을 datastore에 반영을 안하고 있었더라고요 지금까지는 편집했어도 원본 영상으로 올라갔을텐데,, 이것도 수정했습니다
https://github.com/boostcampwm2023/iOS09-Layover/assets/70168249/cb3138b4-92a4-4416-b9d4-7d26cd16cc1d
<br>
- UTType으로 헤더에 mimeType 담아 보내기 → 아직까지 모든 테스트 성공
```swift
guard let mimeType = UTType(filenameExtension: fromFile.pathExtension)?.preferredMIMEType else { throw NetworkError.unknown }
request.setValue(mimeType, forHTTPHeaderField: "Content-Type")
```
<br>
- root뷰컨 변경사항으로 프로그레스바 안보이던 버그 수정
- toast 애니메이션 수정 → fade in, out 되도록 수정했습니다
https://github.com/boostcampwm2023/iOS09-Layover/assets/70168249/466396f5-c4a6-437c-b6ec-b49ca00e92b5
<br>
- 영상 길이 충족 안할시 토스트 추가
close …
=> bug: 업로드 안되는 버그 및 업로드 화면 개선

iOS/Layover/Layover/Network/Provider/Provider.swift, iOS/Layover/Layover/Scenes/BaseViewController.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileInteractor.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileViewController.swift, iOS/Layover/Layover/Workers/Mocks/MockUserWorker.swift, iOS/Layover/Layover/Workers/UserWorker.swift
- MimeType을 기존 PresignedURL 로부터 추출하는 것에서, UTType을 이용해 추출하도록 변경했습니다.
- 네트워킹 시 로딩중임을 보여주고, 유저의 추가적인 입력을 막기 위해 LoadingIndicator 구현했습니다.
> [!NOTE]
> 로딩 인디케이터 기능 구현
- BaseViewController에 LoadingIndicator 기능을 구현해놨습니다.
- 사용 방법도 간단합니다!
```swift
// ViewController 내에서
showLoading()
hideLoading()
```
- 참고로 로딩 인디케이터 뷰가 보이는 상황에서는 로딩 인디케이터 뷰가 최상단에 떠있도록 해놓았기 때문에 
로딩이 끝날 때까지 유저의 추가적인 입력을 신경쓰지 않아도 됩니다.
작동, 구현화면
close #280
=> chore: 프로필 이미지 변경 요청 시 MimeType 추출방식 변경, 로딩 인디케이터 구현

iOS/Layover/Layover/DesignSystem/LOTagStackView.swift, iOS/Layover/Layover/DesignSystem/LOTextField.swift, iOS/Layover/Layover/Scenes/EditTag/EditTagInteractor.swift, iOS/Layover/Layover/Scenes/EditTag/EditTagModels.swift, iOS/Layover/Layover/Scenes/EditTag/EditTagPresenter.swift, iOS/Layover/Layover/Scenes/EditTag/EditTagRouter.swift, iOS/Layover/Layover/Scenes/EditTag/EditTagViewController.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostInteractor.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostModels.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostViewController.swift
작동, 구현화면
https://github.com/boostcampwm2023/iOS09-Layover/assets/70168249/38b869e1-e367-488c-ac26-5c03965899af
close #273
=> feat: 업로드 태그 개수 제한, 필드 글자수 제한

iOS/Layover/Layover/Scenes/Home/HomePresenter.swift, iOS/Layover/Layover/Scenes/Home/HomeViewController.swift, iOS/Layover/LayoverTests/Mocks/Workers/MockHomeWorker.swift, iOS/Layover/LayoverTests/Scenes/Home/HomeInteractorTests.swift, iOS/Layover/LayoverTests/Scenes/Home/HomePresenterTests.swift
- 이미지 로드 방식이 변경됨에 따라 불필요한 썸네일 로드 메서드들을 삭제했습니다.
- 대신 게시글을 전달할 때 썸네일 이미지 데이터(샘플 이미지)까지 전달하는지 확인하는 테스트 메서드를 추가로 구현했고, MockHomeWorker를 수정했습니다.
close #278
=> test: 홈 테스트 코드 수정

iOS/Layover/Layover/Scenes/EditProfile/EditProfileViewController.swift, iOS/Layover/Layover/Scenes/UploadPost/VideoPickerManager.swift
- 처음에는 delegate result에서 identifier를 알 수 있는 방법을 찾지 못해서 우선 사용할 때마다 PHPicekr 인스턴스를 만들어서 사용하도록 했습니다 ! delegate result로 오는 item들은 모두 identifier가 nil이더군요..
- 인환님께서 deselect 메서드 못쓰냐고해서 찾아보니까 `PHPhotoLibrary.shared`를 사용해서 `PHPicker의 Configuration`을 구성하면 delegate의 result로 identifier를 정상적으로 얻어오는 걸 알 수 있었어요!
- `PHPhotoLibrary.shared`은 싱글톤으로 Photos 앱에 의해 관리되는 모든 사진과 비디오의 집합이라고 생각하시면 될 것 같습니다 !
작동, 구현화면
https://github.com/boostcampwm2023/iOS09-Layover/assets/70168249/5ba71eb7-ebd5-4d86-85ad-c7e1f0d75f2d
close #287
=> bug: 업로드, 프로필 편집시 PHPicker 이전에 선택한 것 reset

iOS/Layover/Layover/Network/AuthManager.swift, iOS/Layover/Layover/SceneDelegate.swift, iOS/Layover/Layover/Scenes/Login/LoginWorker.swift, iOS/Layover/Layover/Scenes/Setting/SettingInteractor.swift, iOS/Layover/Layover/Scenes/Setting/SettingViewController.swift, iOS/Layover/Layover/Scenes/SignUpScene/SignUpWorker.swift, iOS/Layover/Layover/Services/System.swift, iOS/Layover/Layover/Services/UserDefaults/UserDefaultStored.swift, iOS/Layover/Layover/Workers/Mocks/StubAuthManager.swift
- 탈퇴 시 안내창 문구 수정
- UserDefaultsWrapper 객체 아카이빙/언아카이빙 방식으로 변경
- 가입, 로그인 시 MemberId/LoginType UserDefaults에 저장하도록 변경
> [!NOTE]
> UserDefaultsWrapper 객체 아카이빙 방식으로 변경
- 기존 구현으로는 UserDefaults에 옵셔널을 저장하기가 어려워서 JSONDecoder/Encoder를 이용한 객체 아카이빙 방식으로 변경하였습니다.
- 이제 반드시 UserDefaults 타입은 옵셔널로 선언해야하고, 꺼내쓸 때 값을 명확히 비교해야 합니다. (변경 코드 참고)
> [!NOTE]
> 회원 가입, 로그인 시 MemberId, LoginType 저장
- 회원 가입, 로그인 시 본인의 MemberId와 로그인 종류를 저장하도록 했습니다.
- AuthManager에서 꺼내어 사용하시면 됩니다.
close #284
=> chore: 탈퇴 시 안내 문구 수정, 회원가입시 memberId UserDefaults에 저장하도록 변경

iOS/Layover/Layover/DesignSystem/LODescriptionView.swift, iOS/Layover/Layover/Network/DTOs/ReportDTO.swift, iOS/Layover/Layover/Network/EndPoint/Factories/DefaultPostManagerEndPointFactory.swift, iOS/Layover/Layover/Scenes/Playback/Cell/PlaybackCell.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackInteractor.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackModels.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackPresenter.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackView.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackViewController.swift, iOS/Layover/Layover/Scenes/Profile/ProfileInteractor.swift, iOS/Layover/Layover/Scenes/Report/ReportConfigurator.swift, iOS/Layover/Layover/Workers/Mocks/MockReportWorker.swift
ReportDTO 변경했습니다.
cell은 영상 먼저 로드하고 프로필 이미지와 로케이션을 로드합니다. 딜레이 부분을 좀 해결한 것 같습니다.
close #289
=> chore: 각종 문제점 개선

iOS/Layover/Layover/Scenes/Playback/Cell/PlaybackCell.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackInteractor.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackModels.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackPresenter.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackViewController.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackWorker.swift, iOS/Layover/Layover/Workers/Mocks/MockPlaybackWorker.swift
authManager에서 memberID가져와 비교해 본인 것이면 삭제, 다른 사람 것이면 신고가 되도록 했습니다.
https://github.com/boostcampwm2023/iOS09-Layover/assets/44396392/2d727dd7-c88e-44bf-8b08-c1f42471f85d
close #295
=> chore: 신고 삭제 로직 분리

iOS/Layover/Layover/Network/AuthManager.swift, iOS/Layover/Layover/Scenes/Login/LoginWorker.swift, iOS/Layover/Layover/Scenes/SignUpScene/SignUpWorker.swift
- memberID 요청 전, 토큰을 먼저 저장하지 않고 요청을 보냈던 오류를 수정했습니다.
- 로그인 메서드에서 memberID 필드를 분리했습니다.
close #312
=> bug: memberID 요청 전, 토큰을 저장하지 않았던 버그 수정

BE/layover/src/board/board.entity.ts, BE/layover/src/board/board.repository.ts
- 생성필드를 추가하고, 태그와 프로필은 최근 생성된 파일부터 보여주도록 설정
=> chore: 태그별, 프로필 영상 최신영상부터 내려줌

iOS/Layover/Layover/Models/Board.swift, iOS/Layover/Layover/Network/DTOs/BoardDTO.swift, iOS/Layover/Layover/Network/Mock/MockData/PostList.json, iOS/Layover/Layover/Network/Mock/MockData/PostListMore.json, iOS/Layover/Layover/Scenes/EditProfile/EditProfileInteractor.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileModels.swift, iOS/Layover/Layover/Scenes/EditProfile/EditProfileViewController.swift, iOS/Layover/Layover/Scenes/Profile/ProfileConfigurator.swift, iOS/Layover/Layover/Scenes/Profile/ProfileInteractor.swift, iOS/Layover/Layover/Scenes/Profile/ProfileModels.swift, iOS/Layover/Layover/Scenes/Profile/ProfilePresenter.swift, iOS/Layover/Layover/Scenes/Profile/ProfileViewController.swift, iOS/Layover/Layover/Scenes/Profile/Views/ThumbnailCollectionViewCell.swift, iOS/Layover/LayoverTests/Mocks/MockDatas/PostList.json, iOS/Layover/LayoverTests/Mocks/MockDatas/PostListMore.json, iOS/Layover/LayoverTests/Scenes/Home/HomeInteractorTests.swift, iOS/Layover/LayoverTests/Scenes/Home/HomeWorkerTests.swift, iOS/Layover/LayoverTests/Scenes/Profile/ProfileInteractorTests.swift, iOS/Layover/LayoverTests/Scenes/Profile/ProfilePresenterTests.swift, iOS/Layover/LayoverTests/Scenes/Profile/ProfileViewControllerTests.swift, iOS/Layover/LayoverTests/Scenes/TagPlayList/TagPlayListInteractorTests.swift, iOS/Layover/LayoverTests/Scenes/TagPlayList/TagPlayListWorkerTests.swift, iOS/Layover/LayoverTests/Seeds.swift
- 프로필 뷰에서 업로드 상태의 영상 로딩 처리
- 프로필 뷰 Pull To Refresh 구현
- 프로필 편집 뷰에서 이미지 편집을 안했음에도 기본 이미지로 변경되는 버그 수정
- 프로필 뷰에서 DisplayModel의 Hashable문제로 DiffableDataSource 크래시 나는 버그 수정
- 변경된 BoardDTO 맞추어 테스트 코드 수정
업로드 처리 중인 셀은 터치 시, 토스트 메시지를 띄우도록 했습니다!
close #299
=> feat: 프로필 뷰에서 업로드 중인 영상 로딩 처리, 각종 버그 수정

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Extensions/URL+.swift, iOS/Layover/Layover/Scenes/Home/Cell/HomeCarouselCollectionViewCell.swift, iOS/Layover/Layover/Scenes/Home/HomeConfigurator.swift, iOS/Layover/Layover/Scenes/Home/HomeViewController.swift, iOS/Layover/Layover/Scenes/Profile/ProfileInteractor.swift, iOS/Layover/Layover/Scenes/UIComponents/LoopingPlayerView.swift, iOS/Layover/Layover/Services/HLSResourceLoader/HLSAssetResourceLoaderDelegate.swift, iOS/Layover/Layover/Services/HLSResourceLoader/HLSSliceResourceLoader.swift
- HLS 세그먼트를 앞부분부터 잘라서 로드할 수 있는 커스텀 리소스 로더 구현
[네이버 Deview 2021 세션](https://tv.naver.com/v/23652319#comment_focus)을 참고해서 구현했습니다.
문제가 우리 앱을 실기기 테스트를 해보니 메모리를 평균 27메가 정도로 상당히 적게 먹어서 홈 캐러셀 쪽은 별로 의미가 없는 것 같네요.
나중에 유경님 여유되시면 맵쪽 캐러셀에 적용해보셔서 실험 해보심 어떨까 합니다.
close #266
=> feat: HLS 세그먼트를 앞부분부터 잘라서 로드시킬 수 있는 커스텀 리소스 로더 구현

iOS/Layover/Layover/Scenes/Map/MapViewController.swift, iOS/Layover/Layover/Scenes/Map/Views/MapCarouselCollectionViewCell.swift
- 지도 셀 커스텀 리소스를 적용했습니다.
- 영상 재생 초반에 black screen이 깜빡이던 현상을 제거했습니다.
작동, 구현화면
https://github.com/boostcampwm2023/iOS09-Layover/assets/70168249/b211f43a-0182-42a0-8ade-12de1d92fce6
close #333
=> chore: 지도 셀 커스텀 리소스 적용 및 black screen flash 현상 제거

iOS/Layover/LayoverTests/Scenes/SignUp/SignUpInteractorTests.swift
signUpInteractorTests에서 빠진 assert 문이 있어서 추가했습니다.
=> test: 빠진 assert문 수정

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/Layover/Layover/AppDelegate.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackView.swift
- HLS 세그먼트 캐싱을 적용했습니다.
- SPM 라이브러리 의존성 추가했고, 우선 재생화면에만 캐싱을 적용시켰습니다.
- AppDelegate에 앱 실행과 함께 프록시 서버 start하고, static 메서드로 url 변환해서 playeritem에 넣어주면 됩니다.
로컬서버에서 ts 세그먼트 로드 할 때, 해당 세그먼트가 캐시에서 나오는지, 서비스 서버에서 가져온 것인지 로그를 찍도록 했습니다.
한번 시청한 동영상은 캐싱이 되는 것을 확인할 수 있습니다.
close #346
=> feat: HLS 캐싱 적용

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/Network/Prefetcher/Prefetcher.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackInteractor.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackViewController.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackWorker.swift, iOS/Layover/Layover/Workers/Mocks/MockPlaybackWorker.swift, iOS/Layover/LayoverTests/Mocks/Workers/MockPlaybackWorker.swift
Prefetcher구현
재생화면에서 collectionView prefetch DataSource 시점에 prefetch 동작
prefetch해서 가져오는게 현재 프로필 이미지, 위치 정보인데 프로필 이미지의 경우 많아봤자 116250 bytes? 정도 밖에 안되는 관계로...
그렇게 큰 이득을 가져오지는 않는 것 같음.
그러나 기존엔 재생화면 빠르게 스크롤 하면 프로필이 조금 늦게 뜨는 경우가 있었는데, prefetch 적용 후 그런 모습은 보이지 않음(cache의 영향도 분명 있음)
prefetcher의 경우 provider가 필요한데 이를 어디서 주입해주는게 좋을지 고민
worker에서 lazy var해서 넣는게 나을지 아니면 그냥 prefetcher가 provider들고 있는게 나을지
지금은 후자의 경우
close #348
=> feat: prefetching을 통한 성능개선 시도

iOS/Layover/Layover.xcodeproj/project.pbxproj, iOS/Layover/Layover/DesignSystem/LOTextLabel.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostInteractor.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostModels.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostPresenter.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostViewController.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostWorker.swift, iOS/Layover/Layover/Services/Location/CurrentLocationManager.swift, iOS/Layover/LayoverTests/Mocks/Workers/MockUploadPostWorker.swift, iOS/Layover/LayoverTests/Scenes/UploadPost/UploadPostInteractorTests.swift, iOS/Layover/LayoverTests/Scenes/UploadPost/UploadPostPresenterTests.swift
업로드시 위치 선택(현재, 영상 위치)기능을 추가했습니다.
action sheet로 나타납니다.
위치 메타데이터 불러오는 법을 몰라 시간이 꽤 걸렸습니다.
UploadPost의 worker와 Interactor등 이곳저곳 건드린 부분 있습니다. 확인 부탁드립니다.
https://github.com/boostcampwm2023/iOS09-Layover/assets/44396392/1bda16a0-d3e8-469d-a464-b5cd89f428aa
close #355
=> feat: 위치 선택 기능 추가

.idea/jsLinters/eslint.xml, .idea/prettier.xml, BE/layover/package-lock.json, BE/layover/src/board/board.controller.spec.ts, BE/layover/src/board/board.controller.ts, BE/layover/src/board/board.repository.ts, BE/layover/src/board/board.service.ts, BE/layover/src/board/board.swagger.ts, BE/layover/src/utils/swaggerUtils.ts
기존의 offset 방식에서 cursor 방식으로 페이징 방식 변경
홈, 태그검색, 프로필 api 요청시 cursor를 추가적으로 날려 페이징 가능.
보내지 않는다면 홈은 랜덤, 태그와 프로필은 최근값을 보여줌
응답에 lastId가 있으므로 해당 값을 다음 요청시에 사용.
데이터가 없다면 빈값을 응답함.
=> feat: cursor 페이징 추가

iOS/Layover/Layover/Scenes/Home/HomeViewController.swift, iOS/Layover/Layover/Scenes/Playback/PlaybackInteractor.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostInteractor.swift, iOS/Layover/Layover/Scenes/UploadPost/UploadPostModels.swift, iOS/Layover/LayoverTests/Scenes/UploadPost/UploadPostPresenterTests.swift
업로드 시 위치 정보가 저장되지 않았던 부분 로직을 수정했습니다.
신고 기능 화면이 뜨지 않던 문제를 해결했습니다.
빌드 타겟을 iOS15로 함에 따라 iOS17에서만 동작하던 코드를 보완했습니다.
close #362
=> bug: 릴리즈 시 발생했던 버그들 수정
